### ISSUE TITLE
`_conflict` should get handled differently

### ISSUE THREAD

**Issue by JPeer264** [JPeer264/node-rcs-core#110]
Sometimes in JS files things get concatenated like:

```js
const myAwesomeNumber = 200;
const newDistanceBetween = myAwesomeNumber + 'px';
```

So when there was already a selector which got renamed to `px` the whole code will get transformed to

```js
const myAwesomeNumber = 200;
const newDistanceBetween = myAwesomeNumber + 'px_conflict';
```

Which is not really correct and would end up breaking the code. I have three suggestions:

1. Removing `_conflict` and just add a warning of all "conflicting" selectors (also add them into the `stats`
2. Removing `_conflict` but add a parameter to allow to add this `markConflictSelectors` (or similar)
3. Leaving `_conflict` but suggest in the readme to ignore those selectors

@X-Ryl669 do you have any suggestions on this?

**Comment by X-Ryl669** [comment]
What I did in my case (almost similar, and due to, for example: `var a = 'title';`) is to exclude all of them.

I don't know if you remember the `Caveat.md` [file](https://github.com/JPeer264/node-rename-css-selectors/pull/45/files?short_path=722d8a4#diff-722d8a43dd56a6b08d3f26a23ad4fc53) I've pushed in `rename-css-selector` repository at the time.

Typically, I think it might be worth to exclude all known conflicting patterns, and they are not legion. Typically, it's HTML tag's name + CSS unit's name. We'll loose a bit of *potential* compression, but safety goes up and likely justify them. 
I can provide my list if you need (the one I'm using in my projects).

So instead of creating an empty exclude list, we can just populate a default exclude list and let the user remove them if she wants to (most won't).

**Comment by JPeer264** [comment]
Ya I remember! (thanks for reminding, I still got the files in the dev branch)

It would be really nice if you could provide your list and we add it to the core.

**Comment by X-Ryl669** [comment]
It's this:
```
{
    "exclude": [
"html", "head", "title", "base", "link", "meta", "style", "body", "article", "section", "nav", "aside", 
"h1", "h2", "h3", "h4", "h5", "h6", "hgroup", "address", "p", "hr", "pre", "blockquote", "ol", "ul", 
"menu", "li", "dl", "dt", "dd", "figure", "figcaption", "main", "div", "a", "em", "strong", "small", 
"s", "cite", "q", "dfn", "abbr", "ruby", "rt", "rp", "data", "time", "code", "var", "samp", "kbd", 
"sub", "sup", "i", "b", "u", "mark", "bdi", "bdo", "span", "br", "wbr", "ins", "del", "picture", 
"source", "img", "iframe", "embed", "object", "param", "video", "audio", "track", "map", "area", 
"table", "caption", "colgroup", "col", "tbody", "thead", "tfoot", "tr", "td", "th", "form", "label", 
"input", "button", "select", "datalist", "optgroup", "option", "textarea", "output", "progress", "meter", 
"fieldset", "legend", "details", "summary", "dialog", "script", "noscript", "template", "slot", "canvas",

"em", "ex", "px", "cm", "mm", "in", "pt", "pc", "ch", "rem", "vmax", "vmin", "vw", "vh", 
"currentcolor"
]
}
```

**Comment by JPeer264** [comment]
Awesome thanks a lot 👍
